server:
  port: 8081
spring:
  thymeleaf:    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  mvc:    favicon:      enabled: false
  #mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jd?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #redis
  redis:    database: 0
    # 服务器地址 
    host: 127.0.0.1
    # 服务器端口
    port: 6379
    # 服务器密码（默认为空）    password: 
    jedis:      pool:
        # 连接池最大连接数（负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（负值表示没有限制）        max-wait: -1
        # 连接池最大空闲链接
        max-idle: 10
        # 连接池最小空闲链接
        min-idle: 0
    # 链接超时时间(毫秒)
    timeout: 1000
#mybatis configure  
mybatis:  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.magicloud.entity
#打印sql语句
logging:  level:     com.magicloud.dao: debug

    
#自定义属性

#人脸图片存放路径
face:
  tempdir: /faceImg/temp/
  dir: /faceImg/image/